# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_breath(object):
    def setupUi(self, breath):
        breath.setObjectName("breath")
        breath.resize(1012, 830)
        self.centralwidget = QtWidgets.QWidget(breath)
        self.centralwidget.setObjectName("centralwidget")
        self.left = QtWidgets.QFrame(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(40, 30, 451, 361))
        self.left.setFrameShape(QtWidgets.QFrame.Box)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.original = QtWidgets.QLabel(self.left)
        self.original.setGeometry(QtCore.QRect(0, 0, 451, 361))
        self.original.setFrameShape(QtWidgets.QFrame.Panel)
        self.original.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.original.setText("")
        self.original.setObjectName("original")
        self.right = QtWidgets.QFrame(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(510, 30, 451, 361))
        self.right.setFrameShape(QtWidgets.QFrame.Box)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.binary = QtWidgets.QLabel(self.right)
        self.binary.setGeometry(QtCore.QRect(0, 0, 451, 361))
        self.binary.setFrameShape(QtWidgets.QFrame.Panel)
        self.binary.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.binary.setText("")
        self.binary.setObjectName("binary")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(80, 740, 121, 41))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(270, 740, 111, 41))
        self.stop.setObjectName("stop")
        self.detect = QtWidgets.QPushButton(self.centralwidget)
        self.detect.setGeometry(QtCore.QRect(630, 740, 111, 41))
        self.detect.setObjectName("detect")
        self.gate = QtWidgets.QPushButton(self.centralwidget)
        self.gate.setGeometry(QtCore.QRect(810, 740, 101, 41))
        self.gate.setObjectName("gate")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 400, 921, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graph_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graph_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_layout.setObjectName("graph_layout")
        breath.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(breath)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 23))
        self.menubar.setObjectName("menubar")
        breath.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(breath)
        self.statusbar.setObjectName("statusbar")
        breath.setStatusBar(self.statusbar)

        self.retranslateUi(breath)
        QtCore.QMetaObject.connectSlotsByName(breath)

    def retranslateUi(self, breath):
        _translate = QtCore.QCoreApplication.translate
        breath.setWindowTitle(_translate("breath", "呼吸检测"))
        self.start.setText(_translate("breath", "start"))
        self.stop.setText(_translate("breath", "stop"))
        self.detect.setText(_translate("breath", "detect"))
        self.gate.setText(_translate("breath", "gate"))
